In [0]:
from __future__ import print_function
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [4]:
#Numpy like package
x = torch.empty(3, 3)
print(x)
x = torch.randn(3, 3)
print(x)
x = torch.zeros(3, 3, dtype=torch.long)
print(x)

tensor([[1.7020e-35, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45]])
tensor([[-0.4578,  0.5747, -0.0118],
        [-1.2636,  0.0858, -1.1756],
        [ 0.2020, -0.4524, -0.7865]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
#tensor
y = torch.tensor([5.5, 3])
x = torch.tensor([5.5, 3])
c=torch.tensor([[1,2,3],[4,5,6]])
print(x)
print("c:",c)
print(x.shape)
print(c.shape)
print(torch.add(x, y))
print(x[0].item())

tensor([5.5000, 3.0000])
c: tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2])
torch.Size([2, 3])
tensor([11.,  6.])
5.5


In [6]:
#resize/reshape 
x = torch.randn(4, 4)
print (x)
y = x.view(16)
z = x.view(-1, 8)# the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())
print(y)


tensor([[ 0.2592, -0.9114, -1.3928, -0.5732],
        [ 0.3774,  1.4340,  1.5644,  1.3881],
        [ 0.1254, -0.4316, -0.3722, -1.2492],
        [ 0.0776,  0.5187,  0.6730, -0.1193]])
torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([ 0.2592, -0.9114, -1.3928, -0.5732,  0.3774,  1.4340,  1.5644,  1.3881,
         0.1254, -0.4316, -0.3722, -1.2492,  0.0776,  0.5187,  0.6730, -0.1193])


In [7]:
# numpy bridge
    #torch to numpy
x = torch.tensor([2, 3])
print(x)
b = x.numpy()
print(b)

    #numpy to torch
import numpy as np
a = np.ones(5,dtype=np.float64)
print (a)
b = torch.from_numpy(a)
print(b)

tensor([2, 3])
[2 3]
[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [8]:
# CUDA Tensors
print(torch.cuda.is_available())
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    print(device)
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    print(x, y)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

False


In [9]:
#To track computation
x = torch.ones(2, 2, requires_grad=True)
a = torch.tensor([[1.0,3.0],[14.0,5.0]])
print("a:",a.requires_grad)
a.requires_grad_(True)
print("a:",a.requires_grad)
print("x:",x)
y = x + a
print("y:",y)

print(y.requires_grad)


a: False
a: True
x: tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
y: tensor([[ 2.,  4.],
        [15.,  6.]], grad_fn=<AddBackward0>)
True


In [10]:
print(x.grad_fn)
print(y.grad_fn)

z = y * y 
#z.requires_grad_(True)
print(z.requires_grad)
print("z:",z)
out = z.mean()
print("out:",out)
out.backward(retain_graph=True)

None
True
z: tensor([[  4.,  16.],
        [225.,  36.]], grad_fn=<MulBackward0>)
out: tensor(70.2500, grad_fn=<MeanBackward0>)


In [11]:
# Gradient 

print(x.grad)
print(out.requires_grad)
print(out.grad)
print(z.grad)
print(y.grad)
print(a.grad)

tensor([[1.0000, 2.0000],
        [7.5000, 3.0000]])
True
None
None
None
tensor([[1.0000, 2.0000],
        [7.5000, 3.0000]])


In [12]:
print(x.requires_grad)
print((x ** 2).requires_grad)

#stop autograd from tracking history on Tensors
with torch.no_grad():
    print((x ** 2).requires_grad)

True
True
False


In [13]:
# different component of neural network
input = torch.randn(1, 3, 32, 32)
m=nn.Conv2d(in_channels=3, out_channels=32, kernel_size=3, stride=1, padding=1 )
print (m.weight.shape)
print (m.bias.shape)
output=m(input)
print(output.shape)

torch.Size([32, 3, 3, 3])
torch.Size([32])
torch.Size([1, 32, 32, 32])


In [14]:
n=nn.MaxPool2d(kernel_size=2,stride=2)
val=n(output)
print(val.shape)

torch.Size([1, 32, 16, 16])


In [15]:
L=nn.Linear(in_features=16*16*32, out_features=16)
val1=L(val.view(val.size(0), -1))
print(val1)
print(L.weight.shape)
print(L.bias.shape)
for param  in L.parameters():
    print(param)

tensor([[ 0.3172, -0.3326, -0.4291, -0.5483, -0.7458,  0.6135, -0.0680, -1.1482,
         -0.2163,  0.0541, -0.5279, -0.0274, -0.3417, -0.4006,  0.2313, -0.1617]],
       grad_fn=<AddmmBackward>)
torch.Size([16, 8192])
torch.Size([16])
Parameter containing:
tensor([[ 0.0033, -0.0036, -0.0016,  ..., -0.0066,  0.0011, -0.0054],
        [ 0.0054, -0.0014, -0.0032,  ..., -0.0088,  0.0018,  0.0019],
        [ 0.0083, -0.0096,  0.0080,  ...,  0.0019, -0.0080, -0.0108],
        ...,
        [-0.0041, -0.0010, -0.0096,  ...,  0.0049,  0.0033, -0.0092],
        [-0.0003, -0.0023,  0.0002,  ..., -0.0020,  0.0065,  0.0109],
        [-0.0077,  0.0060, -0.0079,  ..., -0.0093, -0.0029, -0.0007]],
       requires_grad=True)
Parameter containing:
tensor([-0.0095, -0.0039, -0.0030, -0.0021, -0.0093, -0.0045,  0.0086,  0.0038,
        -0.0039, -0.0064,  0.0058,  0.0067,  0.0003, -0.0022, -0.0082, -0.0071],
       requires_grad=True)


In [16]:
# loss function
loss = nn.MSELoss()
input = torch.randn(3, 5, requires_grad=True)
target = torch.randn(3, 5)
print(input, target)
output = loss(input, target)
output.backward()

tensor([[ 0.8417, -0.3573, -0.3093, -0.3507, -1.3946],
        [ 0.1970,  0.2294, -1.2378, -0.1706,  1.1780],
        [ 0.1001, -1.0833,  2.0406, -0.2515, -0.1425]], requires_grad=True) tensor([[-1.2413, -0.4343, -0.3804, -0.6148, -1.4388],
        [ 0.9747, -0.7249,  0.5390, -1.5846, -1.2599],
        [-1.4772,  1.5003,  0.8167, -1.8498,  1.5182]])


In [17]:
# loss function
loss1 = nn.CrossEntropyLoss()
input = torch.tensor([[0.2,0.3,0.1,0.4],[0.1,0.5,0.2,0.2]], requires_grad=True)
target = torch.tensor([1,3])
print(input, target)
output = loss1(input, target)
output.backward()

tensor([[0.2000, 0.3000, 0.1000, 0.4000],
        [0.1000, 0.5000, 0.2000, 0.2000]], requires_grad=True) tensor([1, 3])


In [0]:
target = torch.randn(1,16)
optimizer = optim.SGD(L.parameters(), lr=0.01, momentum=0.9)
optimizer.zero_grad()
output = L(val.view(val.size(0), -1))
loss = loss(output, target)
loss.backward()
optimizer.step()


In [19]:
print(L.weight.grad)
print(L.bias.grad)

tensor([[ 0.0366,  0.0563,  0.0093,  ...,  0.0295,  0.0266,  0.0405],
        [ 0.0224,  0.0345,  0.0057,  ...,  0.0181,  0.0163,  0.0248],
        [ 0.1559,  0.2399,  0.0399,  ...,  0.1259,  0.1136,  0.1729],
        ...,
        [-0.1181, -0.1817, -0.0302,  ..., -0.0953, -0.0860, -0.1310],
        [-0.0476, -0.0732, -0.0122,  ..., -0.0384, -0.0347, -0.0528],
        [ 0.1478,  0.2274,  0.0378,  ...,  0.1193,  0.1076,  0.1638]])
tensor([ 0.0471,  0.0288,  0.2007, -0.1784, -0.1315,  0.0210,  0.0809, -0.2643,
        -0.0368,  0.2505, -0.3047,  0.0865, -0.0353, -0.1520, -0.0612,  0.1901])
